on:
  release:
    types: [created]

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
        REPO_NAME: informator-69-bot
        REPO_HOME: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: prepare tarball
      run: |
        cd ../
        tar -cvzf $REPO_NAME.tar.gz --exclude-vcs $REPO_NAME
        mv $REPO_NAME.tar.gz $REPO_NAME

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./informator-69-bot.tar.gz,scripts/deploy.sh" 
        target: "deploy"
        strip_components: 1

    - name: deploy
      uses: appleboy/ssh-action@master
      env:
        API_TOKEN: ${{ secrets.API_TOKEN  }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: API_TOKEN
        script: | 
          API_TOKEN=$API_TOKEN ./deploy/deploy.sh

